#;login befor
services:
  db:
    image:  "container-registry.oracle.com/database/enterprise:21.3.0.0"
    #"container-registry.oracle.com/database/free:23.2.0.0"
    restart: always
    environment: 
      - "ORACLE_PWD=oracle"
      # schema of the dump you want to import
      # - "SOURCE_SCHEMA=./database/create_database.ddl"
      # tablespace of the dump you want to import
      # - "SOURCE_TABLESPACE=change-or-delete-me"
    volumes:
      - ./database/setup-scripts:/opt/oracle/scripts/setup
      - ./database/dump:/opt/oracle/dump
    ports:
      - '1521:1521'
    expose:
      - 1521
    deploy:
      resources:
        limits:
          cpus: "2.0"
    # volumes:
    #   - ./database/create_database.ddl:/docker-entrypoint-initdb.d/create_tables.sql
    #   - ./database/insert_example_data.sql:/docker-entrypoint-initdb.d/insert_data.sql