connect c##develop/oracle

CREATE SEQUENCE seq_uzytkownik START WITH 1 INCREMENT BY 1;
--/
CREATE OR REPLACE TRIGGER trg_auto_increment_uzytkownik
BEFORE INSERT ON UZYTKOWNICY
FOR EACH ROW
BEGIN
  :NEW.id_uzytkownika := seq_uzytkownik.NEXTVAL;
END;
/

CREATE SEQUENCE seq_adres START WITH 1 INCREMENT BY 1;
--/
CREATE OR REPLACE TRIGGER trg_auto_increment_adres
BEFORE INSERT ON ADRES_KORESPONDENCJI
FOR EACH ROW
BEGIN
  :NEW.id_adres := seq_adres.NEXTVAL;
END;
/

CREATE SEQUENCE seq_rodzina START WITH 1 INCREMENT BY 1;
--/
CREATE OR REPLACE TRIGGER trg_auto_increment_rodzina
BEFORE INSERT ON CZLONKOWIE_RODZINY
FOR EACH ROW
BEGIN
  :NEW.id_czlonkowie_rodziny := seq_rodzina.NEXTVAL;
END;
/
CREATE SEQUENCE seq_historia START WITH 1 INCREMENT BY 1;
--/
CREATE OR REPLACE TRIGGER trg_auto_increment_historia
BEFORE INSERT ON HISTORIA_STATUSOW_WNIOSKOW
FOR EACH ROW
BEGIN
  :NEW.id_historii := seq_historia.NEXTVAL;
END;
/
CREATE SEQUENCE seq_pola START WITH 1 INCREMENT BY 1;
--/
CREATE OR REPLACE TRIGGER trg_auto_increment_pola
BEFORE INSERT ON POLA_FORMULARZU
FOR EACH ROW
BEGIN
  :NEW.id_pola := seq_pola.NEXTVAL;
END;
/
CREATE SEQUENCE seq_typ START WITH 1 INCREMENT BY 1;
--/
CREATE OR REPLACE TRIGGER trg_auto_increment_typ
BEFORE INSERT ON TYP_FORMULARZU
FOR EACH ROW
BEGIN
  :NEW.id_formularzu := seq_typ.NEXTVAL;
END;
/
CREATE SEQUENCE seq_typ_pola START WITH 1 INCREMENT BY 1;
--/
CREATE OR REPLACE TRIGGER trg_auto_increment_typ_pola
BEFORE INSERT ON TYP_POL_FORMULARZU
FOR EACH ROW
BEGIN
  :NEW.id_typu := seq_typ_pola.NEXTVAL;
END;
/
CREATE SEQUENCE seq_wniosek START WITH 1 INCREMENT BY 1;
--/
CREATE OR REPLACE TRIGGER trg_auto_increment_wniosek
BEFORE INSERT ON WNIOSEK
FOR EACH ROW
BEGIN
  :NEW.id_wniosku := seq_wniosek.NEXTVAL;
END;
/
CREATE SEQUENCE seq_wyplata START WITH 1 INCREMENT BY 1;
--/
CREATE OR REPLACE TRIGGER trg_auto_increment_wyplata
BEFORE INSERT ON WYPLATA
FOR EACH ROW
BEGIN
  :NEW.id_wyplaty := seq_wyplata.NEXTVAL;
END;
/


